### ISSUE TITLE
the path to the install_name_tool is invalid on snow leopard

### ISSUE THREAD

**Issue by catshow** [timthedevguy/BGHUDAppKit#1]
change the path to /Developer/usr/bin/install_name_tool

**Comment by timthedevguy** [comment]
Confirmed

Those of us that did not do a clean leopard install will still function fine, I'm trying to figure out how to do a conditional OS version in the shell script, then it will be fixed.

**Comment by unknowndomain** [comment]
http://www.jiltin.com/index.php/scripts-unix/bash-helphow-do-i-check-if-a-directory-exists-and-display-that-it-doesnt-using-bash/

**Comment by unknowndomain** [comment]
Soloution...

<pre>if [ -f "/usr/bin/install_name_tool" ]; then

    /usr/bin/install_name_tool -change @executable_path/../Frameworks/BGHUDAppKit.framework/Versions/A/BGHUDAppKit @loader_path/../../../../../../../BGHUDAppKit.framework/Versions/A/BGHUDAppKit "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.ibplugin/Contents/MacOS/${PRODUCT_NAME}"

else

    /Developer/usr/bin/install_name_tool -change @executable_path/../Frameworks/BGHUDAppKit.framework/Versions/A/BGHUDAppKit @loader_path/../../../../../../../BGHUDAppKit.framework/Versions/A/BGHUDAppKit "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.ibplugin/Contents/MacOS/${PRODUCT_NAME}"

fi</pre>

**Comment by timthedevguy** [comment]
Nice...thanks for the info, I'll get the put into the repo ASAP. (Net has been down for a few days grrrrrrr)

**Comment by timthedevguy** [comment]
Fixed
