### ISSUE TITLE
Scrollbars ignore the "AppleScrollBarVariant DoubleBoth" option

### ISSUE THREAD

**Issue by EricShapiro** [timthedevguy/BGHUDAppKit#10]
If the global preference AppleScrollBarVariant is set to DoubleBoth, the scrollbars should display two arrows at both ends. This doesn't appear to happen in programs that use GBHUDAppKit.

You can set this option with:
defaults write "Apple Global Domain" AppleScrollBarVariant DoubleBoth

Almost all apps (except notably iTunes) support it.

See:
http://lifehacker.com/5040043/add-double-scroll-arrows-to-both-ends-of-the-scroll-bar

**Comment by timthedevguy** [comment]
The reason I didn't support it is because it was listed as Depreciated in the Docs, didn't realize they still supported it.

**Comment by timthedevguy** [comment]
Won't support due to being Depreciated in HIG Docs
