### ISSUE TITLE
Stepper shows up as red box

### ISSUE THREAD

**Issue by ghost** [timthedevguy/BGHUDAppKit#13]
Did I compile it wrong? It seems to not have been drawn correctly

**Comment by timthedevguy** [comment]
Ooops...Sorry, the stepper control isn't complete, the box your seeing is my drawing boundaries I use as a reference, I'm in the process of figuring out how to detect up or down clicks.

**Comment by ghost** [comment]
Ok, cool. Thanks for the quick reply - thanks for putting this toolkit together, it's been very helpful!

**Comment by timthedevguy** [comment]
Stepper control palette item will be removed to prevent confusion.
