### ISSUE TITLE
Search Field does not honor control size attribute

### ISSUE THREAD

**Issue by xdissent** [timthedevguy/BGHUDAppKit#14]
It looks like the BGHUDSearchFieldCell does not actually scale the magnifying class icon based on the size attribute in IB. The icon placement is adjusted to accommodate the smaller icon, but the "regular" sized icon is always used. Since HUDs are generally very small, simple UI elements, it would be really nice to get this fixed. Great work so far though!

**Comment by timthedevguy** [comment]
I remember I put a TODO note in that class file to allow resizing, I'll take a look.  Thanks!

**Comment by timthedevguy** [comment]
Added support for NSControlSize

Added the support for NSControlSize when drawing the
Search Button and Cancel buttons. Closed by a108f0d1962fce1655459262d9992d1bc31a0d3a
