### ISSUE TITLE
BGHUDBox doesn't understand transparency

### ISSUE THREAD

**Issue by xdissent** [timthedevguy/BGHUDAppKit#16]
Normal boxes can be set transparent or have their transparency bound to some value through IB. While the bindings show up fine, they currently don't change the transparency at all. Is this perhaps due to the way the gradients are rendered?

**Comment by timthedevguy** [comment]
Transparent BGHUDBox

Added checks to draw background based on state of [NSBox isTransparent]
setting.  Closed by 2076e78b6ab6f7e22e19faa091107bf18e8aae15

**Comment by xdissent** [comment]
Thank you!
