### ISSUE TITLE
Horizontal HUD Slider is mislabeled as Vertical Slider

### ISSUE THREAD

**Issue by myshlev** [timthedevguy/BGHUDAppKit#18]
Hello Tim,
I compiled and installed BGHUDAppKit yesterday. I noticed that the Horizontal HUD Slider is mis-identified as "Vertical". The object library description next to the horizontal slider icon says "HUD Vertical Slider - Standard HUD Horizontal Slider". The tooltip and the description in the bottom panel both give the same half-right labeling. The vertical slider is identified correctly. A small problem to be sure, but I thought you should know about it. Thank you for this nice collection of objects.
-Myshkin

**Comment by timthedevguy** [comment]
Thanks!!  Good catch, lol....totally missed that one!

**Comment by timthedevguy** [comment]
Horizontal Slider Typo

Fixes the Horizontal Slider that was mislabeled as
Vertical Slider.  Closed by 324228c51cf9a390aedec6538d0729353eb6af3c
