### ISSUE TITLE
Using an Image Resource in a Pulldown

### ISSUE THREAD

**Issue by ghost** [timthedevguy/BGHUDAppKit#19]
I'm able to add an Image resource for each item in a pulldown for the typical Cocoa pulldowns (Popup button with type=pulldown). When I try this with the BGHUD toolkit, the image doesn't appear. Do I need to do anything to get it to work?

**Comment by timthedevguy** [comment]
I got this to work just fine.  Could you explain what steps I should use in order to reproduce the issue?

![Pulldown Image](http://www.binarymethod.com/images/github19-1.png)

**Comment by ghost** [comment]
Good point - it works fine with text (titles), but if you want a solely iconic pulldown without text, the image goes away. However, this works fine with the standard cocoa pulldown.

**Comment by timthedevguy** [comment]
Still works fine for me, maybe I'm doing something wrong.

![Image](http://www.binarymethod.com/images/github19-2.png)

**Comment by ghost** [comment]
I set the image in the menu item attributes, and removed the title there. Did you do the same? Thanks for the prompt feedback, btw.

**Comment by timthedevguy** [comment]
Aha, found it!  I was leaving the title in place and just selecting the Image Only position in the IB inspector panel.  Doing it your way, deleting the title, does in fact make the image disappear.

**Comment by timthedevguy** [comment]
Pulldown Image Issue
- Assigning an image and deleting the title now properly show the image.  (Without selection Image Only).

I thought I fixed this one last year, Closed by 1b24f8ae9f1ccc655435df4741632c3a504de4fa.
