### ISSUE TITLE
Image resources appear upside down

### ISSUE THREAD

**Issue by ghost** [timthedevguy/BGHUDAppKit#20]
Not sure how to explain this, but sometimes when I add image resources (icos, specifically), after a certain period of time they'll turn upside down. Usually I can delete the resource and re-add it to fix it, though that doesn't always work. Have you seen this?

**Comment by timthedevguy** [comment]
Could you perhaps create a test project and see if it still behaves the same?  If so, email that project to binary.god at gmail dot come.

**Comment by ghost** [comment]
Having trouble reproducing it in a test project - once I get it I will email it to you.

**Comment by timthedevguy** [comment]
Ok, sorry to ask for a test project it's just that I've never seen it happen so far :(

**Comment by timthedevguy** [comment]
Assuming test case could not be reproduced.
