### ISSUE TITLE
NSTableView drop or right click border.

### ISSUE THREAD

**Issue by JamesGreen** [timthedevguy/BGHUDAppKit#23]
Hi,

First of all, great work on the framework!

When I use an NSTableView and I drop something on it or I connect an NSMenu to the NSTableView and right click on a row then I get a -to my eye- ugly blue border in the NSTableView (or its row). This is default behavior and also happens without your framework on Mac OS X 10.5. But I think it's not HUD-ish.
Apple has little to no information about it. All I know is that it's not the focus ring of the first responder.

Anyway, I created 2 screenshots, one with a drop and one with the right click thing. (Sorry that the cell is not visible in the click screenshot but the blue border should be there).

http://img441.imageshack.us/img441/8615/picture2dq.png
http://img209.imageshack.us/img209/8237/picture1wd.png

**Comment by timthedevguy** [comment]
Ok, I see what you mean, your talking about the drop indicator.  I'll see what, if anything, I can do about it.

**Comment by JamesGreen** [comment]
Thank you. Before I posted this I researched some stuff and sadly I couldn't find anything about it. When dropping, you can change the behavior of the blue line with setDropRow:dropOperation: That's all I know..

**Comment by timthedevguy** [comment]
Sadly I can't find any information about this anywhere.  I'll keep it on the back burner but for now it's being closed.
