### ISSUE TITLE
BGHudTextFieldCell Placeholder Text Does Not Respect Alignment

### ISSUE THREAD

**Issue by tylerstillwater** [timthedevguy/BGHUDAppKit#27]
Setting the placeholder text of a HUD Text Field and then setting the alignment to center does not center the placeholder text in the field. The normal text is centered, however.

**Comment by timthedevguy** [comment]
BGHUDTextFieldCell Placeholder Alignment

Fixed improper placeholder alignment in BGHUDTextFieldCell.
Old code would draw left justified at all times, now
responds to -alignment value of BGHUDTextFieldCell.
Closed by 665f421ee7d54b764ff93d81239fd7a1aab77af9.
