### ISSUE TITLE
BGHUDTextFieldCell: Placeholder not rendering in IB

### ISSUE THREAD

**Issue by timthedevguy** [timthedevguy/BGHUDAppKit#30]
Placeholder text not rendering correctly in IB, does not respect the text alignment settings at design time, run time aligns as expected.

**Comment by tylerstillwater** [comment]
I sent you a message about this one. Pretty sure I found the problem. Let me know if it helps! :)

**Comment by timthedevguy** [comment]
Fixed!!  Awesome job!
