### ISSUE TITLE
BGHUDTableViewHeaderCell  &  Column guide off by 1 px

### ISSUE THREAD

**Issue by vade** [timthedevguy/BGHUDAppKit#31]
Hi. BGHudTableView's header is off by 1 px to the right of the columns. Fix is:

add
    frame.origin.x -= 1;
on line 74 (just above     NSRectFill(frame) in _drawThemeContents:) in BGHUDTableViewHeaderCell

Seems to fix it. Thanks for a amazing framework!

**Comment by timthedevguy** [comment]
BGHUDTableViewHeaderCell alignment fix.

Adjusted x coord by 1 pixel to align properly.  Closed by 8a706f1a9b8e365740e88103b45cb14da6e2f964
