### ISSUE TITLE
Plugin+IB: attempt to insert nil value (key: NSColor)

### ISSUE THREAD

**Issue by yene** [timthedevguy/BGHUDAppKit#34]
Xcode 3.2.4 on 10.6.4 core2duo MB
compiled commit http://github.com/binarygod/BGHUDAppKit/commit/14d7b61824a29d0781274c6dd56016f5fdd0f4fe
double-clicked, Interface Builder started and raised an exception: NSInvalidArgumentException Reason: NSCFDictionary setObject:forKey - attempt to insert nil value (key: NSColor)

**Comment by timthedevguy** [comment]
Make sure you have the latest version (looks like you do), make sure you Clean All if you updated an existing directory.  That issue was fixed with that commit.

**Comment by yene** [comment]
thanks
