### ISSUE TITLE
Table view text is not visible when editing cells

### ISSUE THREAD

**Issue by tomaz** [timthedevguy/BGHUDAppKit#37]
Text field cell text has the same color as the background of the field editor. When text is selected it's visible due to highlight having different color, but unselected text is not visible at all...

After playing with it for a while, decided the easiest fix would be to change the cell class of the table view to BGHUDTextFieldCell and setup field editor's background color besides text color.  Here's the code:

```
- (NSText *)setUpFieldEditorAttributes:(NSText *)textObj {
    NSText *newText = [super setUpFieldEditorAttributes: textObj];
    NSColor *textColor = [[[BGThemeManager keyedManager] themeForKey: self.themeKey] textColor];
    NSColor *backColor = [[[BGThemeManager keyedManager] themeForKey: self.themeKey] cellEditingFillColor];
    [(NSTextView *)newText setInsertionPointColor:textColor];
    [(NSTextView *)newText setBackgroundColor:backColor];
    return newText;
}
```

As default BGHUDTableView uses standard NSTableViewCell, each column's cell class needs to be changed to BGHUDTextFieldCell in order for this to work...

**Comment by timthedevguy** [comment]
I will be checking out this issue tomorrow.  I will keep you posted.

**Comment by timthedevguy** [comment]
This appears to be working fine for me, or maybe I'm missunderstanding something.

![TableView Image](http://www.binarymethod.com/github/issue-37.png)

**Comment by tomaz** [comment]
Yep, I noticed, I'm using BGHUDTextFieldCell as column data cell, and it's causing me problems. With default NSTextFieldCell, it's working...

**Comment by timthedevguy** [comment]
You are right though, logicly the Cell class should be BGHUDTextFieldCell, I'm going to change the default operation so that this is the case.  It will take a little time but I'll be working on it in my development branch.
