### ISSUE TITLE
Can't open "old" xibs

### ISSUE THREAD

**Issue by ugol** [timthedevguy/BGHUDAppKit#41]
Cannot open xibs done with old release of BGHudAppkit. IB crashes.

Assertion Message: openEditorForObject: is not re-entrant.

Thread 0 Asserted:
0   InterfaceBuilderKit              0x001b9440 -[IBEditorManager openEditorForObject:closingSubEditors:makeKey:] + 758
1   InterfaceBuilderKit              0x001ad92d -[IBDocument openEditorForObject:closingSubEditors:makeKeyAndOrderFront:] + 498
2   InterfaceBuilderKit              0x0010d3bc -[IBDocument openEditorForObject:makeKeyAndOrderFront:] + 56
3   InterfaceBuilderKit              0x0011f6ff -[IBDocument openEditorForObject:] + 48
4   InterfaceBuilderKit              0x00124033 -[IBEditorWindowController openEditorWithSingleMouseDown:] + 214
5   InterfaceBuilderKit              0x0011d743 -[IBEditorWindowController openEditorWithMouseEvent:] + 629
6   InterfaceBuilderKit              0x00116585 -[IBEditorWindowController interceptEvent:] + 1091
7   InterfaceBuilderKit              0x00116135 -[IBViewEditorWindowController interceptEvent:] + 291
8   InterfaceBuilderKit              0x00115fd7 -[IBEditableWindow sendEvent:] + 70
9   AppKit                           0x97713817 -[NSApplication sendEvent:] + 6431
10  Interface Builder                0x0000464d
11  AppKit                           0x976a72a7 -[NSApplication run] + 917
12  AppKit                           0x9769f2d9 NSApplicationMain + 574
13  Interface Builder                0x000022f5

**Comment by timthedevguy** [comment]
All my old Xibs have opened fine.  Is this a Xib you could possibly share?

**Comment by ugol** [comment]
Thanks Tim, sent privately.

**Comment by timthedevguy** [comment]
We figured this one out privately
