### ISSUE TITLE
checkbox is not visible

### ISSUE THREAD

**Issue by sdevore** [timthedevguy/BGHUDAppKit#42]
Just downloaded and tried out and I am not seeing the check box in interface builder nor in built apps, other controls seem to be working just fine.

**Comment by timthedevguy** [comment]
If this was in an existing application (one that used an earlier version of BGHUDAppKit) did you follow the advice in the readme?  (Toggle the bezel type to something else and back again)

**Comment by sdevore** [comment]
Oh that did work, it was happening in a brand new project.
