### ISSUE TITLE
unable to resolve warnings 'directory not found'

### ISSUE THREAD

**Issue by lulu10** [timthedevguy/BGHUDAppKit#43]
i want to clean up these warnings in my project of 'directory not found' on installs of BGHUDAppKit. i'm assuming that somehow a flag for these directories was created when i did have your framework installed. 

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-7eabd30 2/build/Debug' following -F not found

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-afad22f/build/Release' following -F not found

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-acafd40/build/Release' following -F not found

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-acafd40/build/Release_10.6_10.5_32_64_GC_embed' following -F not found

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-96612b3/build/Debug' following -F not found

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-96612b3/build/Release' following -F not found

It seems that installing and then removing your framework has left this trail behind.

how can i fix this?

ld: warning: directory '/Volumes/Dev/prep_wc/Prep/../../binarygod-BGHUDAppKit-96612b3/build/Release_10.6_10.5_32_64_GC_embed' following -F not found

**Comment by maicki** [comment]
Search in the target settings under the "Framework Search Path" for paths that are not existing anymore

**Comment by timthedevguy** [comment]
Correct, this isn't something BGHUDAppKit did, it's something XCode does automagicly when you add a Framework.  It adds the framework path to "Framework Search Path".

As maicki says just remove any mentions of a BGHUDAppKit path from that setting.

Should work after that! ;)

**Comment by lulu10** [comment]
thank you both for the info. 
that worked!
