### ISSUE TITLE
How to work with XCode 4 

### ISSUE THREAD

**Issue by frankrei** [timthedevguy/BGHUDAppKit#44]
Hi,

With XCode 4 GM released and no support for IB Plug-ins on the horizon, I was wondering what the recommended way of working with BGHUDAppKit is..

Using IB 3 is a stop gap solution but that won't be around forever. I have no idea whether Apple are planning on support plug-ins going forward or not.

What does one have to do to use the classes rather than the plug-in?

Best regards,

Frank

**Comment by sdevore** [comment]
I reported it as a bug in xcode 4 ;)  The release notes to call it a 'known issue' which seems intentionally vague to me

**Comment by timthedevguy** [comment]
In order to use BGHUDAppKit without a plugin just set an NSButton's cell class to BGHUDButtonCell (for example)

IF Xcode 4 IB works like the previous version you click on the button once, then click on it again and your editing the Cell of that button.

I didn't realize XCode4 was out, I'll have to go grab it and see whats what.

**Comment by frankrei** [comment]
Sorry, I haven't had the time to try this yet, but I'm not sure that is what I meant.

My issue is that since I've used the IB Plug-in with IB3 there's some link to that plug-in somewhere in the XIB and when I try to load it without having the plug-in around, it won't let me open it properly.

I presume your advice works on a "clean" xib file, but do you happen to know how to get rid of the association with the plug-in?

Thanks for your help.

**Comment by timthedevguy** [comment]
Ah, woops, yes I misunderstood you.

In your situation you will have to load it in IB 3, remove all instances of BGHUD controls,  save and then load into 4 and it should work.

**Comment by frankrei** [comment]
Hhmm.. I guess that means there's no easy migration path.. oh well, it looks like Apple have taken out the 10.5 SDK at the last moment anyway, so it might be a while before I can do anything with XCode 4 anyways..

**Comment by timthedevguy** [comment]
Hopefully when XCode4 comes out to the public (I don't have an ADC membership) I can figure out an easier way to migrate existing projects.

**Comment by frankrei** [comment]
Thanks.

**Comment by ugol** [comment]
Yes Tim, I thought Xcode 4 was far to be final, but some days ago became GM. That means that probably in a few days (or weeks?) 3.x will be old stuff. (could be for ios 4.3?)
I didn't install it because I don't want to download all that GBs and then download it again, but is definitely worth a look: don't you have someone with ADC access in the neighborhood?

**Comment by sdevore** [comment]
there are going to be some other reasons to hang onto 3.x for example 4 does not include the 10.5 or 10.4 sdk (which is not an option for me  to drop support for).  Be aware if you install the GM or the final when it comes out (I for one hope this GM is not final, it is awfully buggy IMHO) make sure you specify the location or it will remove and replace your 3.x install, or grab a copy of 3.x so you can reinstall.

**Comment by ugol** [comment]
Ok, Xcode 4 is here with 4.3 and Xcode 4 is available also in the App Store.
Tim, I tried your other advice, changing the class of the ButtonCell and doesn't completely work:
- at design time is still drawed "normally". That's not very important but could be annoying if you have to align lot of widgets and there are some differences in normal vs transparent sizes
- at runtime it almost works, but for example the TextField has an opaque background: I had to disable the "draw background" to make it work.

So the situation is not perfect but apparently workable

**Comment by timthedevguy** [comment]
You have to pay for Xcode now?  Really?

**Comment by timthedevguy** [comment]
Lol, checking it out, I don't think i'll buy it today as the servers seem to be major bogged down. I'll wait till monday Ugol and then I'll see what I can figure out ok?

**Comment by ugol** [comment]
No you don't have to, but for mysterious reasons if you don't want/can't subscribe to the free Apple developer you can get xcode 4 from the app store...

**Comment by frankrei** [comment]
Well, if it was free on the App Store, people would be saying "why do I need to pay for a Mac Developer Membership"?

I've not been best pleased with Apple's apparent greed in recent years, but I used to have to pay $500 for the ADC membership, which is now down to $99 and a lot less painful to get hold of and $5 for XCode isn't too bad.. I'm just wondering why it is that Apple can sell applications on the AppStore that require an Installer :-)

**Comment by frankrei** [comment]
I'd be super interested in getting a solution to retrofit existing xib files to run inside of XCode 4 and I'm sure I'm not alone.

So as soon as you've found a way of getting all this working properly, please do a blog post or something.

XCode 4 by the way is awesome (if you forget about 10.5 compatibility and IBPlugins). Big step forward and compares favorably with Eclipse circa 2006.

**Comment by frankrei** [comment]
I'd be super interested in getting a solution to retrofit existing xib files to run inside of XCode 4 and I'm sure I'm not alone.

So as soon as you've found a way of getting all this working properly, please do a blog post or something.

XCode 4 by the way is awesome (if you forget about 10.5 compatibility and IBPlugins). Big step forward and compares favorably with Eclipse circa 2006.

**Comment by ugol** [comment]
ah ah, me too in the $500 ADC: luckily I bought a 17"MBP immediately after and the discount was almost the same :)

About the ADC, xcode can be downloaded with the free membership, so I can't imagine any reason to pay the 5$!

**Comment by timthedevguy** [comment]
Yeah I think the only reason to pay the 5 would be that the App Store would take care of updating Xcode (I would assume).

**Comment by ugol** [comment]
Nope, it appears that free membership means xcode 3. For xcode 4 you have to pay the $5 or be a registered developer.

**Comment by timthedevguy** [comment]
Yeah, I went ahead and paid the 5 ;)  Cheaper than 100, lol.  I have no idea how to even start with BGHUDAppKit now :(  I may have to start one control at a time on a clean 10.6.6 XCode 4 branch.  Ugh...the horror.

**Comment by ugol** [comment]
Some more feedback: I couldn't make checkboxes work, nothing is drawed at runtime after changing the cell to BG*Cell.
BTW, I am in the process of rewriting all the Pomodoro GUI to get rid of ibplugins (I used ShortCutrecorder ibplugin too), so I am in the horror too...

**Comment by timthedevguy** [comment]
Ugol, you can still develop with XCode4 and use plugins, you will just have to edit your Xib with IB3.

Kinda more of a pain than it's worth though, lol

**Comment by timthedevguy** [comment]
ugol,  I have checkboxes working, it requires putting a custom runtime variable in a button on your interface marked as check that has a buttoncell class of BGHUDButtonCell.

Add a variable in the IB inspector window like this:
Name: buttonType
Type: Number
Value: 3

At runtime you will see the normal hud checkbox...this is so gonna make aligning things a pain though.

Please start following @binarymethod on twitter (if you have it)  I'll be posting updates as soon as I can on there.

**Comment by ugol** [comment]
Ok, I am @ugolandini on twitter. Is yours a new account? Apparently the search can't find you (happens sometimes, is a distributed thing)

**Comment by timthedevguy** [comment]
hrmm...you can search by email as well, binary dot god At gmail.com
