### ISSUE TITLE
Can't load interface builder plugin

### ISSUE THREAD

**Issue by countach** [timthedevguy/BGHUDAppKit#45]
I don't know if there is something wrong in my environment or what, but I'm using the latest git version, rebuilt from scratch, but interface builder won't load the plugin, giving an error "The bundle BGHUDAppKitPlugin couldn't be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle". I get this whether trying to open an old .xib file, or trying to manually load the plugin into interface builder from the preferences. I'm using IB and xcode 3.2.5 on the OS-X 10.6.6.

If nobody else is experiencing this, maybe someone could give me a pre-built version of of BGHUDAppKit to try and rule out something about my build. I've been using BGHUDAppKit for a long time, and haven't had this issue before. I can't see any console messages.

**Comment by countach** [comment]
I don't know, I downloaded it from scratch from git, and now the problem isn't there.  Odd.

**Comment by timthedevguy** [comment]
Maybe you downloaded the development branch by mistake?  I changed the way the plugin/framework gets embedded, used @rpath instead of the @loader_path/@executable_path method that is out of date now. (only in the developmental branch though, the master branch hasn't been modified to that yet)
