### ISSUE TITLE
BGHudButtonCell Round Texture Small & Mini render issues

### ISSUE THREAD

**Issue by vade** [timthedevguy/BGHUDAppKit#50]
Small and Mini BGHudButtonCells render the bottom clipped, however Regular size seems to draw fine.

**Comment by timthedevguy** [comment]
Good catch, this must have gotten broken somewhere along the way.

**Comment by timthedevguy** [comment]
ButtonCell Fixes

Closed by 79a560dd8974787f1b81e0726a6985dd29b6bcec - Check Boxes not rendering in IB Plugin, 
the palette item has been removed.

Closed by 79a560dd8974787f1b81e0726a6985dd29b6bcec - Drawing rects for Rounded Texture Button
have been adjusted for Small and Mini sizes.

**Comment by vade** [comment]
Oh man that is awesome and fast. Very appreciated. I love BGHudAppKit, you have done great work here.

**Comment by timthedevguy** [comment]
Thanks vade, glad you find it useful ;)
