### ISSUE TITLE
BGHudButtonCell check box renders invisible

### ISSUE THREAD

**Issue by vade** [timthedevguy/BGHUDAppKit#51]
BGHudButtonCell in Check mode regardless of size renders invisible, with nothing drawn at all (10.6.7)

**Comment by timthedevguy** [comment]
Are you using XCode4?

**Comment by vade** [comment]
No, (3.2.5) but after playing around I realize its only the default checkbox in IB. If you instantiate a say, round-rect button, and then change its type to check, it works. If you choose the slot that is the pre-selected checkbox, it always draws transparent. That makes me believe the IBPlugin is referencing a non-existent class for the NSButton subclass, or something? A screenshot from my IB Library Palette:

http://i.imgur.com/6cqb5.png

that standard HUD Check Box never shows up.However other buttons do, and like I said, changing a working button to a check box seems to be a work around I figured out after posting this bug report.

**Comment by timthedevguy** [comment]
ButtonCell Fixes

Closed by 79a560dd8974787f1b81e0726a6985dd29b6bcec - Check Boxes not rendering in IB Plugin, 
the palette item has been removed.

Closed by 79a560dd8974787f1b81e0726a6985dd29b6bcec - Drawing rects for Rounded Texture Button
have been adjusted for Small and Mini sizes.
