### ISSUE TITLE
NSButton - Small size stroke missing on bottom

### ISSUE THREAD

**Issue by vade** [timthedevguy/BGHUDAppKit#52]
You can see in this image, small style buttons miss their bottom most stroke:

http://i.imgur.com/2G4JT.png

I also think there are some subtle 1 pixel off alignment issues with most of the controls, especially in IB with regards to what it thinks a controls bounds are. I will try to find specifics and let you know.

Thanks again.

**Comment by timthedevguy** [comment]
Vade, sorry for the delay, I worked a 12 hour day yesterday.  I see the issue, I experience it myself during runtime, but during design time in IB they appear fine.  I will start workin on this, I have a super busy week at work this week so I may not get it solved as quick as the last issue.  Thanks.
