### ISSUE TITLE
Rejected from Mac App Store

### ISSUE THREAD

**Issue by Jay-L** [timthedevguy/BGHUDAppKit#53]
The app including this library was rejected from Mac App Store. Please fix someone, it's really sad.

The use of non-public APIs can lead to a poor user experience should these APIs change in the future, and is therefore not permitted. The following non-public APIs are included in your application:

'OBJC_IVAR_$_NSButtonCell._normalImage' in 
'OBJC_IVAR_$_NSScroller.sFlags' in

**Comment by timthedevguy** [comment]
Hi Jay-L, this issue was fixed three months ago, please update your BGHUDAppKit.

**Comment by Jay-L** [comment]
Oh, thank you.
