### ISSUE TITLE
Is it possible to draw the tick marks of a disabled BGSliderCell in the disabledStrokeColor?

### ISSUE THREAD

**Issue by garethsb-ghost** [timthedevguy/BGHUDAppKit#58]
Is it possible to draw the tick marks of a disabled BGSliderCell in the disabledStrokeColor?

I haven't immediately been able to determine how to override the NSSliderCell drawing of the tick marks. However, it's definitely the case that the BGSliderCell track is drawn in the disabledStrokeColor when disabled, but the tick marks aren't rendered differently than in the enabled state.

Is there any way to fix this?

Many thanks,
Gareth

**Comment by apparentsoft** [comment]
Fixed in 983c822 as part of #70
