### ISSUE TITLE
[BGHUDBox cornerRadius] as in NSBox NSBoxCustom and NSLineBorder

### ISSUE THREAD

**Issue by mahal** [timthedevguy/BGHUDAppKit#6]
NSBox with boxType = NSBoxCustom and borderType = NSLineBorder has the ability to draw rounded corners which looks awesome. You can even set the cornerRadius and the borderWidth in Interface Builder with the User Defined Attributes. 

thank you very much for the support and the great BGHUDAppKit.

**Comment by timthedevguy** [comment]
I'm not sure I understand, whats the problem?

**Comment by mahal** [comment]
it's not a problem but a feature request that BGHUDBox will have rounded corners like NSBox (when set the mentioned properties)

**Comment by timthedevguy** [comment]
Ah ok, sorry :)  I'll add that feature request.

**Comment by timthedevguy** [comment]
BGHUDBox corrections
- BGHUDBox now correctly respects cornerRadius and
  borderWidth.  If these values are set then BGHUDBox
  will ignore Shadows and Border selections.  Use Theme
  option will override all settings.  Closed by 8f185e2e10d37df73bed62b03d41be0477f2154d
