### ISSUE TITLE
Access BGHUDAppKit programmatically

### ISSUE THREAD

**Issue by loretoparisi** [timthedevguy/BGHUDAppKit#60]
Hello,
I would know how to access the BGHUD programmatically.

I did something like

// add scrollview
    BGHUDScrollView *scrollview = [[NSScrollView alloc] initWithFrame:NSMakeRect(0.0, 0.0,
                                                                              windowSize.width, windowSize.height-30)];

but a standard NSScrollView comes out.

What's wrong?

Thanks

**Comment by timthedevguy** [comment]
Thats because your using NSScroller initializer and not BGHUDScroller initializer

**Comment by loretoparisi** [comment]
Poor me! You're right! Everything is ok!
